_name_: ratplus16localprefixfgatesimplegqa
d_model: ${model.backbone.d_model}
d_head: 64
num_head: ${eval:${.d_model} // ${.d_head}}
num_kv_head: ${eval:${.num_head} // 4}
k_channel: ${.d_head}
bias: ${model.backbone.bias}
init: ${model.backbone.init}
ln: ${model.backbone.ln}
chunk_size: 1
chunk_size1: 64
local_size: 0
prefix_size: 0
apply_re: false
mix_train: true