_name_: ratplus
d_model: ${model.backbone.d_model}
d_head: 64
num_head: ${eval:${.d_model} // ${.d_head}}
k_channel: ${.d_head}
bias: ${model.backbone.bias}
init: ${model.backbone.init}
ln: ${model.backbone.ln}
dilation_size: 64
local_size: 0
initial_size: 0
apply_re: true
joint_train: true