_name_: ratplus16localprefixfgatesimplehead
d_model: ${model.backbone.d_model}
d_head: 64
num_head: ${eval:${.d_model} // ${.d_head}}
k_channel: ${.d_head}
bias: ${model.backbone.bias}
init: ${model.backbone.init}
ln: ${model.backbone.ln}
chunk_size: 4
chunk_size1: 1
local_size: 0
prefix_size: 0
apply_re: true
mix_train: true